---
- hosts: all
  become: false
  tasks:

  - name: create docker image using war file in Dockerfile
    command: docker build -t simple-devops-image:latest .
    args:
       chdir: /opt/docker

  - name: create tag to image
    command: docker tag simple-devops-image ravigkl/simple-devops-image:latest

  - name: push image onto dockerhub
    command: docker push ravigkl/simple-devops-image

  - name: remove images
    command: docker rmi simple-devops-image:latest ravigkl/simple-devops-image
    ignore_errors: yes