apiVersion: v1
kind: Service
metadata:
  name: devops-test-service
  labels:
    app: devops-test-project
spec:
  selector:
    app: devops-test-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200